# coding: utf-8

"""
    Batch Processing Gateway API

    Batch Processing Gateway API is a RESTful web service to submit, examine and delete Spark jobs.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bpg_api_client.models.dependencies import Dependencies
from bpg_api_client.models.driver_spec import DriverSpec
from bpg_api_client.models.executor_spec import ExecutorSpec
from typing import Optional, Set
from typing_extensions import Self

class SubmitApplicationRequest(BaseModel):
    """
    Submit Application Request
    """ # noqa: E501
    submission_id_suffix: Optional[StrictStr] = Field(default=None, description="If specified, the suffix will be appended to the submission ID", alias="submissionIdSuffix")
    application_name: Optional[StrictStr] = Field(default=None, description="Name of the application. This will help listing submissions under the same application later.", alias="applicationName")
    type: Optional[StrictStr] = Field(default=None, description="Should be: Java / Scala / Python. If not specified, the API will try to figure out by itself.")
    image: Optional[StrictStr] = None
    spot_instance: Optional[StrictBool] = Field(default=None, description="To enable Spot Instance feature that schedules all Spark Executor pods to Spot nodes", alias="spotInstance")
    spark_version: StrictStr = Field(description="Spark version in the format of x.y, where x and y are integers.", alias="sparkVersion")
    main_class: Optional[StrictStr] = Field(default=None, description="The main class in the jar provided in mainApplicationFile for a Java/Scala Spark job", alias="mainClass")
    main_application_file: StrictStr = Field(description="For Java/Scala Spark jobs, provide the full path to the jar file. For PySpark jobs, provide the full path to the Python file.", alias="mainApplicationFile")
    arguments: Optional[List[StrictStr]] = None
    annotations: Optional[Dict[str, StrictStr]] = None
    driver: DriverSpec
    executor: ExecutorSpec
    deps: Optional[Dependencies] = None
    python_version: Optional[StrictStr] = Field(default=None, alias="pythonVersion")
    queue: Optional[StrictStr] = Field(default=None, description="If no queue is specified, a default 'poc' queue will be used.")
    __properties: ClassVar[List[str]] = ["submissionIdSuffix", "applicationName", "type", "image", "spotInstance", "sparkVersion", "mainClass", "mainApplicationFile", "arguments", "annotations", "driver", "executor", "deps", "pythonVersion", "queue"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubmitApplicationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of driver
        if self.driver:
            _dict['driver'] = self.driver.to_dict()
        # override the default output from pydantic by calling `to_dict()` of executor
        if self.executor:
            _dict['executor'] = self.executor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deps
        if self.deps:
            _dict['deps'] = self.deps.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubmitApplicationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "submissionIdSuffix": obj.get("submissionIdSuffix"),
            "applicationName": obj.get("applicationName"),
            "type": obj.get("type"),
            "image": obj.get("image"),
            "spotInstance": obj.get("spotInstance"),
            "sparkVersion": obj.get("sparkVersion"),
            "mainClass": obj.get("mainClass"),
            "mainApplicationFile": obj.get("mainApplicationFile"),
            "arguments": obj.get("arguments"),
            "annotations": obj.get("annotations"),
            "driver": DriverSpec.from_dict(obj["driver"]) if obj.get("driver") is not None else None,
            "executor": ExecutorSpec.from_dict(obj["executor"]) if obj.get("executor") is not None else None,
            "deps": Dependencies.from_dict(obj["deps"]) if obj.get("deps") is not None else None,
            "pythonVersion": obj.get("pythonVersion"),
            "queue": obj.get("queue")
        })
        return _obj


