# coding: utf-8

"""
    Batch Processing Gateway API

    Batch Processing Gateway API is a RESTful web service to submit, examine and delete Spark jobs.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bpg_api_client.api.deletion_api import DeletionApi


class TestDeletionApi(unittest.TestCase):
    """DeletionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeletionApi()

    def tearDown(self) -> None:
        pass

    def test_delete_submission(self) -> None:
        """Test case for delete_submission

        Delete Spark application by submission ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
