# coding: utf-8

"""
    Batch Processing Gateway API

    Batch Processing Gateway API is a RESTful web service to submit, examine and delete Spark jobs.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bpg_api_client.models.get_driver_info_response import GetDriverInfoResponse

class TestGetDriverInfoResponse(unittest.TestCase):
    """GetDriverInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDriverInfoResponse:
        """Test GetDriverInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDriverInfoResponse`
        """
        model = GetDriverInfoResponse()
        if include_optional:
            return GetDriverInfoResponse(
                pod_name = '',
                start_time = 56
            )
        else:
            return GetDriverInfoResponse(
        )
        """

    def testGetDriverInfoResponse(self):
        """Test GetDriverInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
