# coding: utf-8

"""
    Batch Processing Gateway API

    Batch Processing Gateway API is a RESTful web service to submit, examine and delete Spark jobs.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bpg_api_client.models.get_submission_status_response import GetSubmissionStatusResponse

class TestGetSubmissionStatusResponse(unittest.TestCase):
    """GetSubmissionStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSubmissionStatusResponse:
        """Test GetSubmissionStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSubmissionStatusResponse`
        """
        model = GetSubmissionStatusResponse()
        if include_optional:
            return GetSubmissionStatusResponse(
                creation_time = 56,
                spark_application_id = '',
                execution_attempts = 56,
                termination_time = 56,
                duration = 56,
                application_state = '',
                application_error_message = '',
                spark_ui_url = ''
            )
        else:
            return GetSubmissionStatusResponse(
        )
        """

    def testGetSubmissionStatusResponse(self):
        """Test GetSubmissionStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
