# coding: utf-8

"""
    Batch Processing Gateway API

    Batch Processing Gateway API is a RESTful web service to submit, examine and delete Spark jobs.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bpg_api_client.api.examination_api import ExaminationApi


class TestExaminationApi(unittest.TestCase):
    """ExaminationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExaminationApi()

    def tearDown(self) -> None:
        pass

    def test_describe(self) -> None:
        """Test case for describe

        Get spark application spec and related events as a text stream.
        """
        pass

    def test_get_driver_info(self) -> None:
        """Test case for get_driver_info

        Get Spark application driver information.
        """
        pass

    def test_get_log(self) -> None:
        """Test case for get_log

        Get driver/executor stdout logs from EKS
        """
        pass

    def test_get_spark_spec(self) -> None:
        """Test case for get_spark_spec

        Get Spark application spec by submission ID.
        """
        pass

    def test_get_status(self) -> None:
        """Test case for get_status

        Get Spark application status by submission ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
