# coding: utf-8

"""
    Batch Processing Gateway API

    Batch Processing Gateway API is a RESTful web service to submit, examine and delete Spark jobs.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bpg_api_client.api.submission_api import SubmissionApi


class TestSubmissionApi(unittest.TestCase):
    """SubmissionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubmissionApi()

    def tearDown(self) -> None:
        pass

    def test_submit_application(self) -> None:
        """Test case for submit_application

        Submit a Spark application
        """
        pass


if __name__ == '__main__':
    unittest.main()
