# coding: utf-8

"""
    Batch Processing Gateway API

    Batch Processing Gateway API is a RESTful web service to submit, examine and delete Spark jobs.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bpg_api_client.api.health_check_api import HealthCheckApi


class TestHealthCheckApi(unittest.TestCase):
    """HealthCheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthCheckApi()

    def tearDown(self) -> None:
        pass

    def test_healthcheck_status(self) -> None:
        """Test case for healthcheck_status

        Check the current service status
        """
        pass


if __name__ == '__main__':
    unittest.main()
